AllCops:
  NewCops: enable

plugins:
  - rubocop-rake
  - rubocop-rspec

Layout/HeredocIndentation:
  Enabled: true

Style/MultipleComparison:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
